import { useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Activity, AlertCircle, Bell, BookOpen, Check, ChevronRight, CircleDot, Code2, ExternalLink, Flame, GitBranch, GitCommitHorizontal, GitPullRequest, Github, LayoutDashboard, MoreHorizontal, Pin, Plus, Rocket, Search, Settings2, ShieldCheck, Star, Tag, TrendingUp, Users, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type Repo = { name: string; owner: string; description: string; language: string; languageColor: string; stars: string; forks: string; watchers: string; issues: number; updated: string; activity: number; difficulty: "Beginner" | "Intermediate" | "Advanced"; pinned: boolean; alerts: { commits: boolean; issues: boolean; releases: boolean } };
type RepoPreference = { pinned?: boolean; alerts?: Partial<Repo["alerts"]> };
type ActivityItem = { type: "commit" | "issue" | "release" | "pr"; title: string; repo: string; detail: string; time: string };

const navGroups = [
  { label: "MONITORING", items: [{ label: "Dashboard", icon: LayoutDashboard }, { label: "Repositories", icon: BookOpen }] },
  { label: "ACTIVITY", items: [{ label: "Commits Feed", icon: GitCommitHorizontal }, { label: "Issues Tracker", icon: CircleDot }, { label: "PR Watcher", icon: GitPullRequest }] },
  { label: "TOOLS", items: [{ label: "Release Alerts", icon: Bell }, { label: "Repo Search", icon: Search }, { label: "Analytics", icon: TrendingUp }] },
];

function IconButton({ children, label, onClick }: { children: React.ReactNode; label: string; onClick?: () => void }) { return <button aria-label={label} onClick={onClick} className="icon-button">{children}</button>; }
function StatCard({ icon: Icon, label, value, detail, tone }: { icon: React.ElementType; label: string; value: string; detail: string; tone: string }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={18} /></div><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className="stat-detail"><TrendingUp size={13} /> {detail}</div></div>; }
function AlertToggle({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) { return <button className={`alert-toggle ${active ? "active" : ""}`} onClick={onClick} title={`${active ? "Disable" : "Enable"} ${label} alerts`}>{active ? <Check size={11} /> : <X size={11} />} {label}</button>; }

export default function Home() {
  const { user, isAuthenticated } = useAuth();
  const [preferenceOverrides, setPreferenceOverrides] = useState<Record<string, RepoPreference>>({});
  const [activeNav, setActiveNav] = useState("Dashboard");
  const [query, setQuery] = useState("");
  const [showSearch, setShowSearch] = useState(false);
  const [selectedRepoRef, setSelectedRepoRef] = useState<string | null>(null);
  const dashboardQuery = trpc.dashboard.snapshot.useQuery();
  const userDashboardQuery = trpc.dashboard.userSnapshot.useQuery(undefined, { enabled: isAuthenticated });
  const dashboardData = userDashboardQuery.data ?? dashboardQuery.data;
  const monitoringQuery = trpc.monitoring.list.useQuery(undefined, { enabled: isAuthenticated });
  const githubSearchQuery = trpc.github.search.useQuery({ query, page: 1 }, { enabled: query.trim().length >= 2 });
  const detailQuery = trpc.github.repository.useQuery({ repoRef: selectedRepoRef || "facebook/react" }, { enabled: Boolean(selectedRepoRef) });
  const utils = trpc.useUtils();
  const updateMonitoring = trpc.monitoring.update.useMutation({ onSuccess: () => { utils.monitoring.list.invalidate(); utils.dashboard.snapshot.invalidate(); } });
  const persistedByRef = useMemo(() => new Map((monitoringQuery.data ?? []).map(row => [row.monitor.repoRef, row.monitor])), [monitoringQuery.data]);
  const liveRepos = useMemo(() => (dashboardData?.repos ?? []).map(repo => ({ name: repo.name, owner: repo.owner.login, description: repo.description || "No description provided.", language: repo.language || "Mixed", languageColor: repo.language === "TypeScript" ? "#38bdf8" : repo.language === "Go" ? "#22c55e" : repo.language === "Rust" ? "#f97316" : "#f59e0b", stars: repo.stargazers_count >= 1000 ? `${(repo.stargazers_count / 1000).toFixed(1)}k` : `${repo.stargazers_count}`, forks: repo.forks_count >= 1000 ? `${(repo.forks_count / 1000).toFixed(1)}k` : `${repo.forks_count}`, watchers: repo.watchers_count >= 1000 ? `${(repo.watchers_count / 1000).toFixed(1)}k` : `${repo.watchers_count}`, issues: repo.open_issues_count, updated: repo.updated_at ? new Date(repo.updated_at).toLocaleDateString() : "Recently", activity: repo.activity, difficulty: repo.difficulty, pinned: false, alerts: { commits: true, issues: true, releases: false } })), [dashboardData]);
  const hydratedRepos = useMemo(() => liveRepos.map(repo => { const ref = `${repo.owner}/${repo.name}`; const saved = persistedByRef.get(ref); const override = preferenceOverrides[ref]; return { ...repo, pinned: override?.pinned ?? saved?.isPinned ?? repo.pinned, alerts: { ...repo.alerts, ...(saved ? { commits: saved.alertNewCommits, issues: saved.alertNewIssues, releases: saved.alertNewReleases } : {}), ...(override?.alerts ?? {}) } }; }), [liveRepos, persistedByRef, preferenceOverrides]);
  const filteredRepos = useMemo(() => hydratedRepos.filter(repo => `${repo.name} ${repo.owner} ${repo.language}`.toLowerCase().includes(query.toLowerCase())), [hydratedRepos, query]);
  const activityFeed = useMemo(() => (dashboardData?.activity ?? []).map(item => ({ ...item, icon: item.type === "commit" ? GitCommitHorizontal : item.type === "pr" ? GitPullRequest : item.type === "release" ? Tag : CircleDot, accent: item.type === "commit" ? "purple" : item.type === "pr" ? "green" : item.type === "release" ? "gold" : "red" })), [dashboardData]);
  const displayName = user?.name?.split(" ")[0] || "there";
  const initials = (user?.name || "GS").split(" ").map(part => part[0]).join("").slice(0, 2).toUpperCase();
  const stats = dashboardData?.stats;
  const monitoredCount = stats?.activeRepositories ?? 0;
  const starCount = stats?.totalStars ?? 0;
  const openIssueCount = stats?.openIssues ?? 0;
  const releaseCount = stats?.recentReleases ?? 0;
  const streakCount = dashboardData?.streak.current ?? 0;
  const xpCurrent = Math.min(1500, monitoredCount * 90 + streakCount * 50);
  const rank = monitoredCount >= 8 ? "Navigator" : monitoredCount >= 4 ? "Explorer" : "Newcomer";

  const toggleRepo = (name: string, action: "pinned" | "commits" | "issues" | "releases") => {
    const repo = hydratedRepos.find(item => item.name === name); if (!repo) return;
    const next = action === "pinned" ? { isPinned: !repo.pinned } : { [action === "commits" ? "alertNewCommits" : action === "issues" ? "alertNewIssues" : "alertNewReleases"]: !repo.alerts[action] };
    const ref = `${repo.owner}/${repo.name}`;
    setPreferenceOverrides(current => ({ ...current, [ref]: action === "pinned" ? { ...current[ref], pinned: !repo.pinned } : { ...current[ref], alerts: { ...current[ref]?.alerts, [action]: !repo.alerts[action] } } }));
    if (isAuthenticated) updateMonitoring.mutate({ repoRef: ref, ...next });
    toast.success(action === "pinned" ? "Repository pin updated" : "Alert preference updated", { description: name });
  };
  const monitorSearchResult = (repoRef: string) => { if (!isAuthenticated) return toast.info("Sign in to monitor repositories"); updateMonitoring.mutate({ repoRef, isPinned: false, alertNewCommits: true, alertNewIssues: true, alertNewReleases: false }); toast.success("Repository added to monitoring", { description: repoRef }); };
  const handleNav = (label: string) => { setActiveNav(label); if (label !== "Dashboard") toast.info(`${label} view is ready to connect`, { description: "GitHub activity routes are scaffolded for the next data sync." }); };

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Code2 size={19} /></div><span>Git<span>Verse</span></span><div className="brand-pulse" /></div><div className="workspace-chip"><div className="workspace-avatar">{initials}</div><div><strong>Personal space</strong><span>{user?.email || "github.com/your-workspace"}</span></div><ChevronRight size={14} /></div><nav className="side-nav">{navGroups.map(group => <div className="nav-group" key={group.label}><div className="nav-heading">{group.label}</div>{group.items.map(item => <button key={item.label} className={`nav-item ${activeNav === item.label ? "active" : ""}`} onClick={() => handleNav(item.label)}><item.icon size={17} /><span>{item.label}</span>{item.label === "Repositories" && <span className="nav-count">{monitoredCount}</span>}{item.label === "Release Alerts" && <span className="nav-dot" />}</button>)}</div>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Settings2 size={17} /><span>Settings</span></button><div className="profile-card"><div className="profile-avatar">{initials}</div><div className="profile-copy"><strong>{user?.name || "GitVerse user"}</strong><span>{isAuthenticated ? "Connected account" : "Preview workspace"}</span></div><IconButton label="Profile menu"><MoreHorizontal size={17} /></IconButton></div></div></aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={14} /><strong>{activeNav}</strong></div><div className="top-actions"><div className={`search-shell ${showSearch ? "expanded" : ""}`}><Search size={16} /><input value={query} onFocus={() => setShowSearch(true)} onChange={e => setQuery(e.target.value)} placeholder="Search repos, commits, issues..." />{query && <IconButton label="Clear search" onClick={() => setQuery("")}><X size={14} /></IconButton>}<kbd>⌘ K</kbd></div><IconButton label="Notifications" onClick={() => toast.info("Notifications", { description: "New GitHub alerts will appear here." })}><Bell size={18} /><span className="notification-dot" /></IconButton><div className="xp-badge"><Flame size={14} /><span>{xpCurrent.toLocaleString()} XP</span><span className="xp-level">{rank}</span></div></div></header>
      {showSearch && query.trim().length >= 2 && githubSearchQuery.data && <div className="search-results"><div className="search-results-head"><span>PUBLIC GITHUB SEARCH</span><button onClick={() => setShowSearch(false)} aria-label="Close search results"><X size={14} /></button></div>{githubSearchQuery.data.slice(0, 5).map(result => <div key={result.full_name} className="search-result"><div className="repo-icon"><Github size={14} /></div><div><strong>{result.full_name}</strong><span>{result.language || "Mixed language"} · ★ {result.stargazers_count.toLocaleString()}</span></div><button className="monitor-result" onClick={() => monitorSearchResult(result.full_name)}><Plus size={12} /> Monitor</button><ExternalLink size={13} /></div>)}</div>}
      <div className="page-container"><section className="hero-row"><div><div className="eyebrow"><span className="live-dot" /> LIVE WORKSPACE</div><h1>Good morning, {displayName} <span className="wave">👋</span></h1><p>Here’s what’s happening across your monitored repositories.</p></div><button className="outline-button" onClick={() => dashboardQuery.refetch()}><Activity size={15} /> Sync now</button></section><section className="hero-metrics"><div className="hero-metric"><span>{monitoredCount}</span><small>Repos Monitored</small></div><div className="hero-divider" /><div className="hero-metric"><span>{streakCount} <Flame size={20} /></span><small>Day Streak</small></div><div className="hero-divider" /><div className="hero-metric"><span>{rank}</span><small>Current Rank</small></div><div className="level-progress"><div className="level-heading"><span>Next level</span><strong>{xpCurrent} / 1,500 XP</strong></div><div className="progress-track"><div className="progress-fill purple" style={{ width: `${Math.max(0, (xpCurrent / 1500) * 100)}%` }} /></div><span className="level-caption">{Math.max(0, 1500 - xpCurrent)} XP to <strong>Navigator</strong></span></div></section><section className="stats-grid"><StatCard icon={GitBranch} label="Active Repositories" value={monitoredCount.toLocaleString()} detail={dashboardQuery.isLoading ? "Loading GitHub" : "Live from GitHub"} tone="purple" /><StatCard icon={Star} label="Total Stars" value={starCount >= 1000 ? `${(starCount / 1000).toFixed(1)}k` : starCount.toLocaleString()} detail="Across monitored repos" tone="gold" /><StatCard icon={AlertCircle} label="Open Issues" value={openIssueCount.toLocaleString()} detail="Across monitored repos" tone="red" /><StatCard icon={Rocket} label="Recent Releases" value={releaseCount.toLocaleString()} detail="From GitHub activity" tone="green" /></section>
        <div className="content-grid"><section className="repos-panel panel"><div className="panel-heading"><div><div className="section-kicker">MONITORED REPOSITORIES</div><h2>My repos <span>({filteredRepos.length})</span></h2></div><div className="heading-actions"><button className="filter-button" onClick={() => setQuery("")}><span className="filter-active" /> All repos <ChevronRight size={14} /></button><IconButton label="Add repository" onClick={() => setShowSearch(true)}><Plus size={17} /></IconButton></div></div><div className="repo-list">{filteredRepos.map(repo => <article className="repo-card" key={`${repo.owner}/${repo.name}`}><div className="repo-top"><div className="repo-icon"><Github size={17} /></div><div className="repo-title"><div><h3>{repo.name}</h3><span className="repo-owner">{repo.owner}</span></div><button className={`pin-button ${repo.pinned ? "pinned" : ""}`} aria-label={`${repo.pinned ? "Unpin" : "Pin"} ${repo.name}`} onClick={() => toggleRepo(repo.name, "pinned")}><Pin size={15} /></button></div></div><p className="repo-description">{repo.description}</p><div className="repo-meta"><span><i className="language-dot" style={{ background: repo.languageColor }} />{repo.language}</span><span className={`difficulty ${repo.difficulty.toLowerCase()}`}>{repo.difficulty}</span><span className="updated">Updated {repo.updated}</span></div><div className="repo-activity"><div className="activity-label"><span>Activity level</span><strong>{repo.activity}%</strong></div><div className="progress-track"><div className={`progress-fill ${repo.activity > 75 ? "purple" : repo.activity > 50 ? "blue" : "gold"}`} style={{ width: `${repo.activity}%` }} /></div></div><div className="repo-footer"><div className="repo-stats"><span><Star size={13} /> {repo.stars}</span><span><GitBranch size={13} /> {repo.forks}</span><span><Users size={13} /> {repo.watchers}</span><span><CircleDot size={13} /> {repo.issues}</span></div><div className="alert-controls"><AlertToggle label="C" active={repo.alerts.commits} onClick={() => toggleRepo(repo.name, "commits")} /><AlertToggle label="I" active={repo.alerts.issues} onClick={() => toggleRepo(repo.name, "issues")} /><AlertToggle label="R" active={repo.alerts.releases} onClick={() => toggleRepo(repo.name, "releases")} /></div></div><button className="repo-detail-link" onClick={() => setSelectedRepoRef(`${repo.owner}/${repo.name}`)}>View activity <ExternalLink size={12} /></button></article>)}{!filteredRepos.length && <div className="empty-state"><Github size={24} /><strong>{isAuthenticated ? "No monitored repositories yet" : "Connect your GitHub workspace"}</strong><span>{isAuthenticated ? "Use public search above to add your first repository." : "Sign in to load your own monitored repositories."}</span>{isAuthenticated && <button className="outline-button" onClick={() => setShowSearch(true)}><Search size={14} /> Search public repos</button>}</div>}</div></section>
        <aside className="right-column"><section className="panel streak-panel"><div className="panel-heading compact"><div><div className="section-kicker">CONSISTENCY</div><h2>Commit streak</h2></div><button className="text-button">This week <ChevronRight size={13} /></button></div><div className="streak-total"><div className="streak-flame"><Flame size={22} /></div><div><strong>{streakCount} days</strong><span>Computed from monitored commits</span></div></div><div className="week-row">{["M", "T", "W", "T", "F", "S", "S"].map((day, index) => { const dayValue = dashboardData?.streak.days[index] ?? 0; return <div className="day-cell" key={`${day}-${index}`}><span>{day}</span><div className={`day-orb ${dayValue > 0 && index < 6 ? "complete" : index === 6 && dayValue > 0 ? "today" : ""}`}>{dayValue > 0 ? index === 6 ? <Flame size={13} /> : <Check size={12} /> : null}</div><small>{dayValue || "–"}</small></div>; })}</div></section><section className="panel activity-panel"><div className="panel-heading compact"><div><div className="section-kicker">LAST 24 HOURS</div><h2>Today’s Activity</h2></div><IconButton label="Activity options"><MoreHorizontal size={17} /></IconButton></div><div className="activity-list">{activityFeed.map(item => <div className="activity-item" key={`${item.repo}-${item.title}`}><div className={`activity-icon ${item.accent}`}><item.icon size={15} /></div><div className="activity-copy"><strong>{item.title}</strong><span><b>{item.repo}</b> · {item.detail}</span></div><time>{item.time}</time></div>)}{!activityFeed.length && <div className="activity-empty">No recent activity in the monitored workspace.</div>}</div><button className="view-all" onClick={() => setActiveNav("Commits Feed")}>View full activity <ChevronRight size={14} /></button></section><section className="quick-card"><div className="quick-icon"><ShieldCheck size={19} /></div><div><strong>Read-only connection</strong><span>GitVerse only requests safe GitHub access.</span></div><ChevronRight size={16} /></section></aside></div></div></main>
    {selectedRepoRef && <div className="detail-backdrop" onClick={() => setSelectedRepoRef(null)}><section className="detail-drawer" onClick={event => event.stopPropagation()}><div className="detail-drawer-head"><div><div className="section-kicker">REPOSITORY ACTIVITY</div><h2>{selectedRepoRef}</h2></div><IconButton label="Close repository activity" onClick={() => setSelectedRepoRef(null)}><X size={17} /></IconButton></div>{detailQuery.isLoading && <div className="detail-loading">Loading GitHub activity…</div>}{detailQuery.error && <div className="detail-loading">GitHub activity could not be loaded for this repository.</div>}{detailQuery.data && <div className="detail-content"><div className="detail-summary"><span><Star size={14} /> {detailQuery.data.repo.stargazers_count.toLocaleString()}</span><span><GitBranch size={14} /> {detailQuery.data.repo.forks_count.toLocaleString()}</span><span><CircleDot size={14} /> {detailQuery.data.repo.open_issues_count.toLocaleString()}</span></div><div className="detail-columns"><div><h3><GitCommitHorizontal size={14} /> Commits</h3>{detailQuery.data.commits.slice(0, 4).map(commit => <div className="detail-row" key={commit.sha}><strong>{commit.commit.message.split("\n")[0]}</strong><span>{commit.sha.slice(0, 7)} · {commit.commit.author?.name || "GitHub author"}</span></div>)}</div><div><h3><CircleDot size={14} /> Issues</h3>{detailQuery.data.issues.slice(0, 4).map(issue => <div className="detail-row" key={issue.number}><strong>#{issue.number} {issue.title}</strong><span className={issue.state === "open" ? "state-open" : "state-closed"}>{issue.state}</span></div>)}</div><div><h3><GitPullRequest size={14} /> Pull requests</h3>{detailQuery.data.pullRequests.slice(0, 4).map(pr => <div className="detail-row" key={pr.number}><strong>#{pr.number} {pr.title}</strong><span>{pr.state} · {pr.user?.login || "author"}</span></div>)}</div><div><h3><Tag size={14} /> Releases</h3>{detailQuery.data.releases.slice(0, 4).map(release => <div className="detail-row" key={release.tag_name}><strong>{release.tag_name} {release.name}</strong><span>{release.published_at ? new Date(release.published_at).toLocaleDateString() : "Unpublished"}</span></div>)}</div></div></div>}</section></div>}
    {!isAuthenticated && <div className="auth-toast"><div className="auth-toast-icon"><Github size={17} /></div><div><strong>Connect your GitHub workspace</strong><span>Sign in to personalize your repository data.</span></div><div className="auth-buttons"><button className="auth-google" onClick={() => startLogin()}><Github size={13} /> Google</button><button className="auth-email" onClick={() => startLogin()}>Email</button></div></div>}
  </div>;
}
